---
.github/workflows/ci.yml:
  with:
    additional_packages: libaugeas-dev augeas-tools
Gemfile:
  optional:
    ':test':
      - gem: ruby-augeas
spec/spec_helper.rb:
  spec_overrides:
    - "require 'fixtures/modules/augeasproviders_core/spec/support/spec/psh_fixtures'"
    - "require 'augeas_spec'"
    - "# augeasproviders: setting $LOAD_PATH to work around broken type autoloading"
    - "$LOAD_PATH.unshift(File.join(__dir__, 'fixtures/modules/augeasproviders_core/lib'))"
    - "$LOAD_PATH.unshift(File.join(__dir__, 'fixtures/modules/sshkeys_core/lib'))"
    # Allow for proper monkey patching of the sshkeys provider
    - "$LOAD_PATH.unshift(File.join(__dir__, 'fixtures/modules/augeasproviders_ssh/lib'))"
spec/spec_helper_acceptance.rb:
  unmanaged: false
